const { toUpper, isNaN, toLower, chain, partition, get } = require('lodash');
const { commentIfDeactivated } = require('./commentDeactivatedHelper');

module.exports = app => {
	const templates = require('../configs/templates');
	const assignTemplates = app.require('@hackolade/ddl-fe-utils').assignTemplates;
	const { toString } = require('./general')(app);

	const decorateType = (type, columnDefinition) => {
		type = toUpper(type);
		let resultType = type;

		if (isTimestamp(type)) {
			if (columnDefinition.timePrecision && !isNaN(columnDefinition.timePrecision)) {
				resultType = `${type}(${columnDefinition.timePrecision})`;
			}
		}

		if (['VARCHAR', 'CHAR', 'CHARACTER', 'VARBYTE'].includes(type)) {
			if (columnDefinition.length && !isNaN(columnDefinition.length)) {
				resultType = `${type}(${columnDefinition.length})`;
			}
		}

		if (['NUMBER', 'DECIMAL', 'NUMERIC'].includes(type)) {
			if (!isNaN(columnDefinition.scale) && !isNaN(columnDefinition.precision)) {
				resultType = `${type}(${Number(columnDefinition.precision)},${Number(columnDefinition.scale)})`;
			}
		}

		return resultType;
	};

	const isString = type =>
		['VARCHAR', 'NVARCHAR', 'TEXT', 'CHAR', 'CHARACTER VARYING', 'BPCHAR', 'CHARACTER', 'NCHAR'].includes(
			toUpper(type),
		);

	const isTimestamp = type => ['TIME', 'TIMESTAMP', 'TIMESTAMPTZ', 'TIMETZ'].includes(toUpper(type));

	const escapeString = str => str.replace(/^'([\S\s]+)'$/, '$1').replace(/'/g, "''");

	const getDefault = (type, defaultValue) => {
		const constantsValues = ['current_timestamp', 'current_user', 'null'];

		if (isString(type) && !constantsValues.includes(toLower(defaultValue))) {
			return `'${escapeString(String(defaultValue))}'`;
		} else if (toUpper(type) === 'BOOLEAN') {
			return toUpper(defaultValue);
		}

		return defaultValue;
	};

	const hasValue = value => value !== '' && value !== null && value !== undefined;

	const getIdentity = identity => {
		if (!identity) {
			return '';
		}

		const prefix = identity.generateIdentity === 'by default' ? 'GENERATED BY DEFAULT AS IDENTITY' : 'IDENTITY';

		if (!hasValue(identity.seed) && !hasValue(identity.step)) {
			return ` ${prefix}`;
		}

		const seed = Number(get(identity, 'seed', 0));
		const step = Number(get(identity, 'step', 1));

		return ` ${prefix}(${seed}, ${step})`;
	};

	const getQuota = (quotaSize, isUnlimited) => {
		if (isUnlimited) {
			return ' QUOTA UNLIMITED';
		}
		if (quotaSize) {
			return ` QUOTA ${quotaSize} MB`;
		}
		return '';
	};

	const getSourceSchemaNameForExternalSchema = (postgresSchemaName, redshiftSchemaName, source) => {
		const schemaRequiredSources = ['Redshift', 'Postgres'];
		const schemaName = postgresSchemaName || redshiftSchemaName;
		if (schemaName && schemaRequiredSources.includes(source)) {
			return ` SCHEMA "${schemaName}"`;
		}
		return '';
	};
	const getARN = (arn, source) => {
		const ARNRequiredSources = ['MYSQL', 'Postgres'];
		if (arn && ARNRequiredSources.includes(source)) {
			return ` SECRET_ARN ${arn}`;
		}
		return '';
	};

	const getUri = (uri, port, source) => {
		const uriRequiredSources = ['Hive metastore', 'Postgres', 'MYSQL'];
		if (!uriRequiredSources.includes(source)) {
			return '';
		}
		if (uri && port) {
			return ` URI ${uri} PORT ${port}`;
		} else if (uri) {
			return ` URI ${uri}`;
		}
		return '';
	};

	const getColumnComments = (tableName, columnDefinitions) => {
		return chain(columnDefinitions)
			.filter('comment')
			.map(columnData => {
				const comment = assignTemplates(templates.comment, {
					object: 'COLUMN',
					objectName: `${tableName}."${columnData.name}"`,
					comment: toString(columnData.comment),
				});

				return commentIfDeactivated(comment, columnData);
			})
			.join('')
			.value();
	};

	const createColumnsStatements = columns => columns.map(column => column.statement).join(',\n\t');

	const getColumnsDefinitions = (columns, isParentActivated) => {
		const [activatedColumns, deactivatedColumns] = partition(
			columns,
			column => !isParentActivated || column?.isActivated,
		);
		const activatedStatements = createColumnsStatements(activatedColumns);
		const deactivatedStatements = createColumnsStatements(deactivatedColumns);
		const isDeactivatedStatements = deactivatedStatements.length;
		const commentedDeactivatedStatements = isDeactivatedStatements
			? '\n\t' + commentIfDeactivated(deactivatedStatements, { isActivated: false }, true)
			: '';

		return `${activatedStatements}${commentedDeactivatedStatements}`;
	};

	return {
		getQuota,
		getIdentity,
		getSourceSchemaNameForExternalSchema,
		getUri,
		getARN,
		decorateType,
		getDefault,
		getColumnComments,
		getColumnsDefinitions,
	};
};
