const DROP_STATEMENTS = ['DROP SCHEMA', 'DROP TABLE', 'DROP FUNCTION', 'DROP PROCEDURE', 'DROP COLUMN', 'DROP VIEW'];

const ROW_FORMAT_TYPES = Object.freeze({
	DELIMITED: 'DELIMITED',
	SERDE: 'SERDE',
});

const STORED_AS_TYPES = Object.freeze({
	INPUT_OUTPUT_FORMAT: 'INPUTFORMAT / OUTPUTFORMAT',
});

module.exports = {
	DROP_STATEMENTS,
	ROW_FORMAT_TYPES,
	STORED_AS_TYPES,
};
